option-as-alt = 'left'
theme = "catppuccin-frappe"

[cursor]
style = "Block"
blinking = false

[fonts]
family = "FiraCode Nerd Font Mono"
size = 18

[navigation]
mode = "BottomTab"

[shell]
program = "/opt/homebrew/bin/fish"
args = []
